### ISSUE TITLE
When open some special window, rbinkdeys is keep crashed

### ISSUE THREAD

**Issue by zw963** [kui/active_window_x#3]
Following app is a example.

[razorsql](https://razorsql.com/download.html) linux 64bit version.

When open razorsql in slackware 14.2, connections menu -> connect -> select a profile
press connection button, active_window_x is crashed with following logs:

```sh
/home/public/Dropbox/linux/utils/linux_key_rebinding/app/lib/active_window_x/window.rb:94:in `x_get_window_property': BadWindow (invalid Window parameter) (ActiveWindowX::Xlib::XErrorEvent)
        from /home/public/Dropbox/linux/utils/linux_key_rebinding/app/lib/active_window_x/window.rb:94:in `prop_raw'
        from /home/public/Dropbox/linux/utils/linux_key_rebinding/app/lib/active_window_x/window.rb:76:in `prop'
        from /home/public/Dropbox/linux/utils/linux_key_rebinding/app/lib/active_window_x/root_window.rb:11:in `active_window'
        from /home/public/Dropbox/linux/utils/linux_key_rebinding/app/lib/active_window_x/event_listener.rb:95:in `listen_with_no_select'
        from /home/public/Dropbox/linux/utils/linux_key_rebinding/app/lib/rbindkeys/observer.rb:99:in `handle_x_event'
        from /home/public/Dropbox/linux/utils/linux_key_rebinding/app/lib/rbindkeys/observer.rb:77:in `block (2 levels) in start'
        from /home/public/Dropbox/linux/utils/linux_key_rebinding/app/lib/rbindkeys/observer.rb:75:in `each'
        from /home/public/Dropbox/linux/utils/linux_key_rebinding/app/lib/rbindkeys/observer.rb:75:in `block in start'
        from /home/public/Dropbox/linux/utils/linux_key_rebinding/app/lib/rbindkeys/observer.rb:62:in `loop'
        from /home/public/Dropbox/linux/utils/linux_key_rebinding/app/lib/rbindkeys/observer.rb:62:in `start'
        from /home/public/Dropbox/linux/utils/linux_key_rebinding/app/lib/rbindkeys/cli.rb:73:in `observe'
        from /home/public/Dropbox/linux/utils/linux_key_rebinding/app/lib/rbindkeys/cli.rb:36:in `call'
        from /home/public/Dropbox/linux/utils/linux_key_rebinding/app/lib/rbindkeys/cli.rb:36:in `main'
        from /home/public/Dropbox/linux/utils/linux_key_rebinding/bin/..//app/bin/rbindkeys.rb:8:in `<main>'
```

**Comment by zw963** [comment]
@kui , I fixed with change handle x event method to:

```rb
  def handle_x_event
      event = @window_observer.listen_with_no_select   # <==  this code raise exception.
      return if event.nil? or event.window.nil?

      @event_handler.active_window_changed event.window
    rescue ActiveWindowX::Xlib::XErrorEvent => e
      LOG.error e
    end
```
